service: sms-rest

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 30
  region: 'us-west-2'
  stage: debug
  deploymentBucket: 'sree-sms-api'
  environment:
    REST_LOG_LEVEL: 'debug'
    SMS_LAMBDA_NAME: 'sree-sms-debug-sms'

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "rds:*"
      Resource: "*" # <-- TODO THIS IS BAD
    - Effect: "Allow"
      Action:
        - "lambda:*"
      Resource: "*"

package:
  exclude:
    - node_modules/aws-sdk/**

functions:
  rest:
    handler: index.handler
    environment:
      SMS_LAMBDA_NAME: 'sree-sms-debug-sms'
      SMS_LAMBDA_REGION: 'ap-southeast-1'
      STAGE_NAME: 'debug'
    events:
      - http:
          path: /{proxy+}
          method: any
          request:
            passThrough: WHEN_NO_MATCH

plugins:
  - serverless-plugin-typescript
